[package]
name = "vulkan-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37.3", features=["loaded"]}
glfw = {version = "0.54.0", features=["vulkan"]}


